### ISSUE TITLE
Compiling help: [BRIEF DESCRIPTION / ERROR MESSAGE OUTPUT]

### ISSUE THREAD

**Issue by Enchantedbooz** [Twingamerdudes/XGen#2]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [X] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.

Warning: Ignoring unknown fps=""
C:/Users/?/remove/discord_rpc/git/discord_rpc/DiscordRpc.hx:213: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
                                                          source/Alphabet.hx:198: characters 20-28 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
                                                              source/Main.hx:70: characters 61-65 : Float should be Int
                                                                                                                       source/Main.hx:70: characters 61-65 : ... For optional function argument 'updateFramerate'
                                                                                         source/Main.hx:70: characters 61-65 : ... For function argument 'child'
                                        export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
                source/PlayState.hx:62: characters 21-29 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
                    C:/Users/?/remove/polymod/git/polymod/Polymod.hx:1005: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
                                                                    C:/Users/JD/remove/polymod/git/polymod/Polymod.hx:1051: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
                                                                                                                    C:/Users/?/remove/polymod/git/polymod/backends/PolymodAssets.hx:226: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
                                                          source/PlayState.hx:110: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
                                                               source/PlayState.hx:426: characters 38-46 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
                                                                    source/PlayState.hx:1308: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
                                                                          source/PlayState.hx:1310: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
                                                                                source/PauseSubState.hx:23: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
                                                                                        source/PauseSubState.hx:29: characters 20-28 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
                                                                                                source/ChartingState.hx:83: characters 13-21 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
                                                                                                        source/ChartingState.hx:488: characters 16-24 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound

**Comment by Twingamerdudes** [comment]
XGen has been abandoned for years; the libraries it was using could have become updated over time. For now, I would move to psych engine or FNF 0.4.0b for doing modding stuff
